Veri madenciliğini Python programlama dili kullanarak yapacağız demiştik. Bu noktada önemli bilmemiz gereken kütüphaneler var. Bunlardan birincisi ve en temeli aslında Numpy kütüphanesi. Sonraki derslerde göreceğimiz kütüphaneler de zaten numpy üzerine kurulu olacak o nedenle temel bir numpy eğitiminin faydalı olacağını düşündük tabii sadece veri madenciliği olarak düşünmeyin bu kütüphaneyi bilimsel hesaplamalar diyebileceğimiz tüm hesaplamalarınızda kullanabilirsiniz. Bilimsel veya teknik hesaplamaların tamamını neredeyse NumPy üzerinde yapabilirsiniz. O nedenle bir de bu kulakla dinleyip gözle takip edip ellerinizle de kodları denerseniz sevinirim. Nedir diye başlayalım. 

Numpy nümerik python dan geliyor. Numerical computing yapıyor nümerik hesaplamalar. Demek ki nümerik veriler ile ilgileneceğiz. 

NumPy dizileri ile Python içerisindeki listelere benzer şekilde bir kullanıma sahiptir. Ancak listeler ile yapılamayan çok boyutlu diziler için NumPy çok daha kullanışlı bir yapı sunmaktadır. Bu nedenle veri madenciliği için gerekli hesaplamalar için sıklıkla NumPy kullanılmaktadır. Numpy bize çok boyutta tanımlayabileceğimiz bir veri yapısı sunuyor data structure. Çok zengin metotlar veya fonksiyonlara sahip.

Kendi sayfasından daha detaylı bilgi alınabilir. Numpy.org sayfası birincil kaynak olacak. Bu sayfayı dersten sonra incelersiniz faydalı olacaktır. Community e bakın documentation lara bakın gibi genel bilgilerini edinmeyi size bırakıyorum. Şimdi biz jupyter notebook üzerinden devam edelim.

Öncelikle numpy kütüphanesini çağıralım. Bakın Numpy kütüphanesi diyorum buna kütüphane dersek daha doğru olur. Bir pyton kodlarından oluşan ve içerisinde sınıf sınıflara ait metotlar özellikler olan dosyaya modül modüllerin olduğu klasöre paket birden fazla paketin olduğu içeriklere de kütüphane denilir. O nedenle kütüphane daha doğru paket de denilebilir ama biz kütüphane diyelim en doğrusu öyle olur. Çağıralım kütüphaneyi.

In [2]:
import numpy as np # böyle de çağırılabilir import numpy diye veya
# from numpy import array veya from numpy import array as arr denilebilir.
np.__version__ # versiyonlar önemli demiştik. Pandas versiyonunda sorun olmuştu.

'1.19.2'

Eğer bu komut hata veriyorsa numpy paketi yüklü olmayabilir yükledik beraber anaconda içerisinde geldi ama diyelim ki bir şekilde silinmiş. Bunu kontrol için aşağıdaki kodları yazabiliriz

In [ ]:
!conda list # hangi paketlerin yüklü olduğunu gösterir.

In [ ]:
# eğer yüklü değilse yüklemek için 
!conda install numpy

Başlarken belirtelim bir fonksiyon ya da metotla ilgili yardım dokümanına ulaşmak için help fonksiyonunu kullanabiliriz. Ya da sonuna ? işareti koyarak gidebiliriz.

In [ ]:
help(np) # numpy hakkında yardıma ulaştık.

In [ ]:
np?

In [ ]:
np.

NumPy'ın temelinde çok boyutlu diziler var. Multidimensional arrays. Diziler python'daki listelerden geliştirilmiş. Listelerden farklı olarak Array içerisindeki değişkenlerin tipleri aynı olacak. Pythonda biliyorsunuz herşey bir obje sınıfa ait bir obje ya da nesne buradaki en önemli nesne de ndarray. Bunu görelim.

In [3]:
np.ndarray?
# shape: tuple olarak dizinin şekli hakkında bilgi verir.
# size: dizinin büyüklüğü hakkında bilgi verir. Kaç adet eleman var bilgisi.
# Ndim: Dizinin kaç boyutlu olduğu hakkında bilgi verir.
# nbytes: Verilerin ne kadar yer tuttuğunu söyler.
# dtype: Tutulan elemanların hangi tipte veri olduğunu söyler. 

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

Şimdi bir dizi oluşturalım ve onun üzerinde bu bilgileri gösterelim.

In [4]:
veriler = np.array([1,2,3])

In [5]:
veriler.shape

(3,)

In [6]:
veriler.size

3

In [7]:
veriler.ndim

1

In [8]:
veriler.nbytes

12

In [9]:
veriler.dtype
# integer, 32, 64, 16, 8 olabiliyor.

dtype('int32')

In [21]:
# dtype parametresi değiştirilebilir.
np.array([1,2,4], dtype=np.float)

array([1., 2., 4.])

In [43]:
# veri tipi dönüşümü aşağıdaki gibi yapılabilir.
veriler = np.array(veriler, dtype=float)

In [44]:
veriler.dtype

dtype('float64')

In [10]:
veriler_iki_boyutlu = np.array([[1,2,3],[4,5,6]])
veriler_iki_boyutlu.ndim

2

In [14]:
veriler_iki_boyutlu.size

6

In [13]:
veriler_iki_boyutlu.shape

(2, 3)

In [15]:
veriler_iki_boyutlu.ndim

2

In [16]:
# 3 boyutu da hayal edebileceğiz ama sonrası hayal sınırlarını zorlar.
# hayal dahi edemeyiz o nedenle 3 boyutta kalalım ama
# daha fazla boyutta da olabileceğini bilelim.
veriler_uc_boyutlu = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [20]:
veriler_uc_boyutlu.shape
# 1 satır 3 sütündan oluşan 3 adet dizi

(1, 3, 3)

In [26]:
# burayı biraz görselleştirelim
# arama yapalım 3 dimensions arrays in numpy
# küpler gibi düşünebilirsiniz. Bu renkli küpler var onlar gibi aynı renkleri biraraya getirmeye çalıştığımız küpler
# aman diyeyim 4 boyutlu diziler nasıl gösterilir diye düşünmeye çalışmayın fazla zorlarsınız beyninizi. 
 

In [23]:
x3 = np.array([[
                [1,2],
                [2,3],
                [[4,6],[7,8]],[9,10],[11,12]]])

ipykernel_launcher:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [24]:
x3.shape

(1, 5, 2)

In [59]:
# 10 adet 0'dan oluşan dizi
print(np.zeros(10, dtype=int))
# 3 satır 5 sütun içerisinde 1'lerden oluşan dizi 
print(np.ones((3, 5), dtype=float))
# 3.14'lerden oluşan dizi
print(np.full((3, 5), 3.14))
# Birim matris
print(np.eye(3))

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# [0,5) arasındaki tam sayılar
print(np.arange(5))
# [3,7) arasındaki tam sayılar
print(np.arange(3,7))
# [0, 10) arasındaki tam sayıları 3'er artması
print(np.arange(0,10,3))


[0 1 2 3 4]
[3 4 5 6]
[0 3 6 9]


In [56]:
# [0,9) arasındaki tam sayıların 3 satır 3 sütunda yazılması
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
# [0,9) arasındaki tam sayılardan eşit aralıkta 3 sayı getirme
np.linspace(0,9,3)

array([0. , 4.5, 9. ])

In [62]:
# rassal sayı üretecinin sabitlenmesi
np.random.seed(0)
# 1 ile 10 arasında 3 adet tam sayı üret
r1 = np.random.randint(low=1, high=10,size=3)
print(r1)
# 4 adet 0-1 arasında sayı üret
r2 = np.random.random(4)
print(r2)

[6 1 4]
[0.85794562 0.84725174 0.6235637  0.38438171]


In [72]:
# Belirli şekilde sayı üret
# 3 satır 5 sütundan oluşan sayılar
np.random.seed(0)
r3 = np.random.randint(10, size=(3,5))
print(r3)
# ortalaması 10 standart sapması 2 olan normal dağılıma uyan sayı üret
r4 = np.random.normal(10,2,size=(10,))
print(r4)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]]
[10.28808714 12.90854701 11.52207545 10.24335003 10.88772647 10.66734865
 12.98815815  9.58968347 10.6261354   8.29180852]


In [73]:
x1 = np.random.randint(10, size=6) # Tek boyutlu dizi
x2 = np.random.randint(10, size=(3, 4)) # iki boyutlu dizi
x3 = np.random.randint(10, size=(3, 4, 5)) # üç boyutlu dizi

In [74]:
print(x1[0]) # tek boyutlu dizinin ilk elemanı
print(x1[-1]) # sondan ilk eleman
print(x1[-2]) # sondan ikinci eleman
print(x2[0, 0])  # ilk satır, ilk sütun
print(x2[2, 0])  # ikinci satır, ilk sütun


9
3
7


In [75]:
# x[start:stop:step] ile dizi içerisinde dilimleme yapılabilir.
x = np.arange(10)  # 0-10 arasındaki sayılar
print(x[:5])  # ilk 5 eleman
print(x[5:])  # 5 elemandan sonrası
print(x[4:7])  # 4. ve 7 elemanlar arası
print(x[::2])  # tüm elemanlar iki iki artır
print(x[::-1])  # elemanları ters çevir
print(x[5::-2])  # 5 ten sonrasını bir sonraki olacak şekilde ters çevir

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [76]:
print(x2[:2, :3])  # 2 satır, 3 sütun
print(x2[:3, ::2])  # ilk 3 satır, sonraki olacak şekilde sütunlar
print(x2[::-1, ::-1])  # satırları ve sütunları ters çevir
print(x2[:, 0])  # ilk sütundaki tüm satırlar
print(x2[0, :])  # ilk satırdaki tüm sütunlar

[[2 7 2]
 [0 4 5]]
[[2 2]
 [0 5]
 [6 4]]
[[1 4 8 6]
 [5 5 4 0]
 [0 2 7 2]]
[2 0 6]
[2 7 2 0]


In [78]:
# iç içe diziler(nested) için dilimleme işlemleri
ic_ice = np.array([1,2,[3,4,5, [6,7,8]]])
print(ic_ice[0])
print(ic_ice[2])

1
[3, 4, 5, [6, 7, 8]]
ipykernel_launcher:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [79]:
print(ic_ice[3])
# dizi aslında 3 elemanlı 3. eleman da bir dizi.


IndexError: index 3 is out of bounds for axis 0 with size 3

In [82]:
# bu dizi de 4 elemanlı 4. elemanı da bir dizi.
ic_ice[2][3]

[6, 7, 8]

In [81]:
ic_ice[2][3][2]

8

In [6]:
# x için excel de tablo çizelim.


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [13]:
x # tüm veriler

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [9]:
x[0] # birinci satır veriler

array([5, 0, 3, 3])

In [8]:
x[2,:] # üçüncü satır tüm sütunlardaki veriler

array([2, 4, 7, 6])

In [10]:
x[:,2] # tüm satırdakiler ve üçüncü sütundaki veriler

array([3, 3, 7])

In [11]:
x[[0,2],[1]] # birinci ve üçüncü satırdaki ve ikinci sütundaki veriler

array([0, 4])

In [12]:
x[1:3,1:3] # ikinci ve üçüncü satırdaki ikinci ve üçüncü sütundaki veriler

array([[9, 3],
       [4, 7]])

In [14]:
# mantıksal sınama
x < 5  # 5'ten küçük olanlara True yazar

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [15]:
x[x < 5]  # 5 ten küçük olanları getir

array([0, 3, 3, 3, 2, 4])

In [18]:
x % 3 == 0 # 3 ile bölünebilen yerlere doğru yazdırır

array([[False,  True,  True,  True],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [19]:
x[x % 3 == 0] # 3 ile bölünebilen sayıları getirir.

array([0, 3, 3, 9, 3, 6])

In [20]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # kaç sefer var
print("-x = ", -x)
print("x ** 2 = ", x**2)  # karesi
print("x % 2 = ", x % 2)  # mod bölümünden kalan

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [21]:
-(0.5 * x + 1)**2 # dizideki elemanları 0.5 ile çarp 1 ekle, karesini al - ile çarp

array([-1.  , -2.25, -4.  , -6.25])

In [22]:
abs(-(0.5 * x + 1)**2)  # mutlak değer

array([1.  , 2.25, 4.  , 6.25])

In [23]:
print(np.sum(x))  # dizideki elemanların toplamı
print(np.min(x))
print(np.max(x))
print(np.std(x))  # standart sapma
print(np.var(x))  # varyans
print(np.argmin(x))  # minimum değerin indexi
print(np.argmax(x))
print(np.median(x))
print(np.percentile(x, q=25))

6
0
3
1.118033988749895
1.25
0
3
1.5
0.75


In [24]:
A = np.array([1,2,3])
B = np.array([[4],[5],[6]])

In [25]:
A*B

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [26]:
np.dot(A,B)

array([32])

In [27]:
# Şekil dönüşümleri
A.reshape(3,1)

array([[1],
       [2],
       [3]])

In [35]:
B

array([[4],
       [5],
       [6]])

In [34]:
B.transpose() # sütunları satır satırları sütuna çevirir.

array([[4, 5, 6]])

In [38]:
C = np.zeros((2, 2))
D = np.ones((2, 2))
np.vstack((C, D)) # D dizisini C dizisinin altına koyar

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [39]:
np.hstack((C,D)) # D dizisini C dizisinin sağ tarafına koyar

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [44]:
E = np.eye(2)
np.column_stack((C, D, E)) # sütunlarda birleştirir

array([[0., 0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 0., 1.]])

In [45]:
np.row_stack((C, D, E)) # satırlarda birleştirir

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.]])

In [46]:
# Dizilerin kopyalanması

In [47]:
a1 = np.array([1, 2, 3])
b1 = a1
b1

array([1, 2, 3])

In [49]:
a1[0] = 99 # a1'deki değişiklik b1'i etkileyecektir.
b1

array([99,  2,  3])

In [50]:
# copy işlemi
a1 = np.array([1, 2, 3])
b1 = a1.copy()
a1[0] = 99
b1 # a1'deki değişiklik b1'i etkilemeyecektir.

array([1, 2, 3])

In [51]:
# Veri kaydetme ve okuma

In [53]:
np.save("a1_data", a1) # bu şekilde .npy dosyası kaydı gerçekleştirilir.

In [54]:
okunan_a1 = np.load("a1_data.npy")
okunan_a1

array([99,  2,  3])

In [56]:
np.savetxt("a1_txt.txt", a1) 

In [58]:
a1_txt_okunan = np.loadtxt("a1_txt.txt")
a1_txt_okunan

array([99.,  2.,  3.])

In [62]:
np.savetxt("a1_txt.txt", a1, fmt='%.2i') # iki basamaklı tam sayı formatı

In [64]:
titanic_verileri = np.genfromtxt("titanic.csv", delimiter=',', names=True)

In [66]:
titanic_verileri[0]

(1., 0., 3., nan, nan, nan, 22., 1., 0., nan, 7.25, nan, nan)